default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: "password"
  host: db

production:
  <<: *default
  database: sample_rails_development

development:
  <<: *default
  database: sample_rails_development

test:
  <<: *default
  database: sample_rails_test