default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: "password"
  host: db

production:
  <<: *default
  database: lk4r9wk7dp9wfdpk
  username: xz303h2ekci165je
  password: cuvne6id32wkv8ob
  host: v02yrnuhptcod7dk.cbetxkdyhwsb.us-east-1.rds.amazonaws.com
  url: mysql2://xz303h2ekci165je:cuvne6id32wkv8ob@v02yrnuhptcod7dk.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/lk4r9wk7dp9wfdpk

development:
  <<: *default
  database: sample_rails_development

test:
  <<: *default
  database: sample_rails_test